# This file contains the application's default configuration values. To override properties for a
#particular profile, you can create an application-PROFILE (e.g. application-prod.yml).

variables:
  CONTEXT_PATH: v1/mps/knowing/customers


#mock server base url
mockserver_base_url: localhost:8089/mock

#Enable Tomcat server log. By default, the access logs aren't enabled. We can specify the format as below.
server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %h request:"%r" response_code:%s response_time_ms:%D bytes_sent:%b query_string:"%q"'
      directory: /dev
      prefix: stdout
      suffix: ""
      file-date-format: ""
      buffered: false

jwt:
  secret: secret-terces

spring:
  cloud:
    vault:
      uri: http://localhost:8200
      token: hvs.7s5Rl3GOqPrGQ1tmDMBCfCrz



max_retry_attempts_to_call_pega: 32
a: 12
b: 8

tree:
  retry: 3


downstream-services:
  timeout: 5