DROP TABLE IF EXISTS KB_EMPLOYEES;

CREATE TABLE KB_EMPLOYEES (
                               id INT PRIMARY KEY, /* we could make key auto generated by writing AUTO_INCREMENT */
                               first_name VARCHAR(250) NOT NULL,
                               last_name VARCHAR(250) NOT NULL,
                               email VARCHAR(250) DEFAULT NULL
);

